//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radical_Ecart_UserManagementService
{
    using System;
    using System.Collections.Generic;
    
    public partial class exception
    {
        public string ExceptionMessage { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string InnerExceptionMessage { get; set; }
        public string MethodName { get; set; }
        public string Id { get; set; }
    }
}
